//------------------------------------------------------------------------------------------------------------------//
// Name: Dylan Shortt
// Group: 1
// Student Number: ST-10438409
//------------------------------------------------------------------------------------------------------------------//

//------------------------------------------------------------------------------------------------------------------//
// Reference: 
// GitHub Copilot. (2025). AI programming assistant. [online] Available at: https://copilot.github.com/ [Accessed: 2025].
//------------------------------------------------------------------------------------------------------------------//

//------------------------------------------------------------------------------------------------------------------//
// <summary>
// These import statements are used to import the necessary libraries for the program to run.
// </summary>
using System;
//------------------------------------------------------------------------------------------------------------------//

//------------------------------------------------------------------------------------------------------------------//
// <summary>
// The namespace is used to group classes that are logically related.
// </summary>
namespace PROG_6221_ST10438409_Part_2
{
    //------------------------------------------------------------------------------------------------------------------//
    // <summary>
    // The ConsoleFormat class is used to format the console output.
    // </summary>
    public class ConsoleFormat
    {
        //------------------------------------------------------------------------------------------------------------------//
        // <summary>
        // This method will print a border around the chatbot text
        // </summary>
        public static string PrintBorder()
        {
            //-------------------------------------------------//
            // Print a border around the chatbot text
            String message = "--------------------------------------------------";
            return message;
            //-------------------------------------------------//            
        }
        //------------------------------------------------------------------------------------------------------------------//

        //------------------------------------------------------------------------------------------------------------------//
        // <summary>
        // This method will print a border around the text and maintain consistent formatting
        // </summary>
        public static void PrintBorderWithColour()
        {
            ConsoleColor currentColor = Console.ForegroundColor;
            ConsoleColor borderColor = ConsoleColor.DarkGray;
            Console.ForegroundColor = borderColor;
            Console.WriteLine(PrintBorder());
            Console.ForegroundColor = currentColor;
        }
        //------------------------------------------------------------------------------------------------------------------//

        //------------------------------------------------------------------------------------------------------------------//
        // <summary>
        // This method creates the symbol for the chatbot
        // the art for this program was generated by ChatGPT
        // </summary>
        public static string CreateSymbol()
        {
            //-------------------------------------------------//
            // Display a computer (laptop) that has a lock symbol on the screen            
            String symbol = @"
                /|  /|  ---------------------------
                ||__||  |                         |
               /   O O\__    Cybersecurity        |
              /          \   Support Chatbot      |
             /      \     \                       |
            /   _    \     \ ----------------------
           /    |\____\     \      ||
          /     | | | |\____/      ||
         /       \| | | |/ |     __||
        /  /  \   -------  |_____| ||
       /   |   |           |       --|
       |   |   |           |_____  --|
       |  |_|_|_|          |     \----
       /\                  |
      / /\        |        /
     / /  |       |       |
 ___/ /   |       |       |
|____/    c_c_c_C/ \C_c_c_c";
            //-------------------------------------------------//

            return symbol;
        }
        //------------------------------------------------------------------------------------------------------------------//

        //------------------------------------------------------------------------------------------------------------------//
        // <summary>
        // Method that displays the cybersecurity-themed symbol using ASCII art.
        // </summary>
        public static void DisplaySymbol()
        {
            //-------------------------------------------------//
            //get symbol 
            string symbol = CreateSymbol();
            //-------------------------------------------------//

            //-------------------------------------------------//
            // Display the symbol in green text
            Console.ForegroundColor = ConsoleColor.Cyan;
            PrintBorderWithColour();
            Console.WriteLine(symbol);
            PrintBorderWithColour();
            Console.ResetColor();
            //-------------------------------------------------//
        }
        //------------------------------------------------------------------------------------------------------------------//

        //------------------------------------------------------------------------------------------------------------------//
        // <summary>
        // This method switches the chatbot and user text colour to green and white respectively.
        // </summary>
        public static void SwitchTextColour(int colourSwitch)
        {

            if (colourSwitch == 0)
            {
                //-------------------------------------------------//
                // Switch the text colour to green
                Console.ForegroundColor = ConsoleColor.Green;
                return;
                //-------------------------------------------------//
            }
            else
            {
                //-------------------------------------------------//
                // Switch the text colour to white
                Console.ForegroundColor = ConsoleColor.White;
                return;
                //-------------------------------------------------//
            }
        }
        //------------------------------------------------------------------------------------------------------------------//
    }
    //------------------------------------------------------------------------------------------------------------------//
}
//-----------------------------------...ooo000 END OF FILE 000ooo...-----------------------------------//